version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs_app
    restart: unless-stopped  # Esto hace que el contenedor se reinicie automáticamente si el servidor se apaga
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      # Para desarrollo podrías montar el código, pero en producción solo montamos datos persistentes
      - ./public:/app/public
      # Cache de node_modules para no reinstalar todo cada vez
      - node_modules:/app/node_modules
    networks:
      - nextjs_network

volumes:
  node_modules:
  # postgres_data:

networks:
  nextjs_network:
    driver: bridge