export const dataTest = [
  {
    name: "0121 Alfonso Flores",
    fullPath: "/home/admin/0121 Alfonso Flores",
    timestamp: "25 May 2025, 04:08:00 PM",
    children: [],
    directory: true,
    file: false,
  },
  {
    name: "19011297 Cristofer",
    fullPath: "/home/admin/19011297 Cristofer",
    timestamp: "25 May 2025, 04:08:00 PM",
    children: [
      {
        name: "Test",
        fullPath: "/home/admin/Test",
        timestamp: "25 May 2025, 04:08:00 PM",
        children: [],
        directory: true,
        file: false,
      },
    ],
    directory: true,
    file: false,
  },
  {
    name: "Bases de Datos y Bases de Conocimiento_040425.pptx",
    fullPath: "/home/admin/Bases de Datos y Bases de Conocimiento_040425.pptx",
    timestamp: "25 May 2025, 04:15:00 PM",
    children: [],
    directory: false,
    file: true,
  },
  {
    name: "BD_Diagrama.png",
    fullPath: "/home/admin/BD_Diagrama.png",
    timestamp: "25 May 2025, 04:30:00 PM",
    children: [],
    directory: false,
    file: true,
  },
  {
    name: "GRACIAS POR SUPERAR TODOS LOS OBSTA.txt",
    fullPath: "/home/admin/GRACIAS POR SUPERAR TODOS LOS OBSTA.txt",
    timestamp: "25 May 2025, 04:31:00 PM",
    children: [],
    directory: false,
    file: true,
  },
  {
    name: "Proyecto 01 - Especificaciones de entrega.pdf",
    fullPath: "/home/admin/Proyecto 01 - Especificaciones de entrega.pdf",
    timestamp: "25 May 2025, 04:08:00 PM",
    children: [],
    directory: false,
    file: true,
  },
  {
    name: "Reporte Preliminar 2025 Gonzalo-modificado.docx",
    fullPath: "/home/admin/Reporte Preliminar 2025 Gonzalo-modificado.docx",
    timestamp: "25 May 2025, 04:08:00 PM",
    children: [],
    directory: false,
    file: true,
  },
  {
    name: "track.flac",
    fullPath: "/home/admin/track.flac",
    timestamp: "25 May 2025, 04:41:00 PM",
    children: [],
    directory: false,
    file: true,
  },
  {
    name: "track.mp3",
    fullPath: "/home/admin/track.mp3",
    timestamp: "25 May 2025, 04:08:00 PM",
    children: [],
    directory: false,
    file: true,
  },
  {
    name: "video.mp4",
    fullPath: "/home/admin/video.mp4",
    timestamp: "25 May 2025, 04:41:00 PM",
    children: [],
    directory: false,
    file: true,
  },
];
